print("matriz 3×3")
print()
a00 = int(input("digite a posiçao da linha 1 coluna 1: "))
a01 = int(input("digite a posiçao da linha 1 coluna 2: "))
a02 = int(input("digite a posiçao da linha 1 coluna 3: "))
a10 = int(input("digite a posiçao da linha 2 coluba 1: "))
a11 = int(input("digite a posiçao da linha 2 coluna 2: "))
a12 = int(input("digite a posiçao da linha 2 coluna 3: "))
a20 = int(input("digite a posiçao da linha 3 coluna 1: "))
a21 = int(input("digite a posiçao da linha 3 coluna 2: "))
a22 = int(input("digite a posiçao da linha 3 coluna 3: "))
print()
print("[[   {0}   {1}   {2}   : {0}   {1}   ]]\n[[   {3}   {4}   {5}   : {3}   {4}   ]]\n[[   {6}   {7}   {8}   : {6}   {7}   ]] ".format(a00,a01,a02,a10,a11,a12,a20,a21,a22))
print()
print("calculando o 'D' ")
dp = (a00 * a11 * a22) + (a01 * a12 * a20) + (a02 * a10 * a21)
ds = (a02 * a11 * a20) + (a00 * a12 * a21) + (a01 * a10 * a22)
d = (dp) - (ds)
print("diagonal principal do 'D' deu: ", dp)
print("diagonal secundaria do 'D' deu: ", ds)
print("resultado de 'D' eh: ", d)
print("------------------------------")

t = int(input("digite o termo independente da linha um   "))
t1 = int(input("digite o termo independente da linha dois "))
t2 = int(input("digite o termo independente da lilha tres "))
print()
print("[[   {0}   {1}   {2}   : {0}   {1}   ]]\n[[   {3}   {4}   {5}   : {3}   {4}   ]]\n[[   {6}   {7}   {8}   : {6}   {7}   ]] ".format(t,a01,a02,t1,a11,a12,t2,a21,a22))
print()
print("calculando o 'D×' ")
dxp = (t * a11 * a22) + (a01 * a12 * t2) + (a02 * t1 * a21)
dxs = (a02 * a11 * t2) + (t * a12 * a21) + (a01 * t1 * a22)
dx = (dxp) - (dxs)
print("diagonal principal do 'D×' deu: ", dxp)
print("diagonal secundaria do 'D×' deu: ", dxs)
print("resultado de 'D×' eh: ", dx)
print("------------------------------")
print()
print("[[   {0}   {1}   {2}   : {0}   {1}   ]]\n[[   {3}   {4}   {5}   : {3}   {4}   ]]\n[[   {6}   {7}   {8}   : {6}   {7}   ]] ".format(a00,t,a02,a10,t1,a12,a20,t2,a22))
print()
print("calculando o 'Dy' ")
dyp = (a00 * t1 * a22) + (t * a12 * a20) + (a02 * a10 * t2)
dys = (a02 * t1 * a20) + (a00 * a12 * t2) + (t * a10 * a22)
dy = (dyp) - (dys)
print("diagonal principal do 'Dy' deu: ", dyp)
print("diagonal secundaria do 'Dy' deu: ", dys)
print("resultado de 'Dy' eh: ", dy)
print("------------------------------")
print()
print("[[   {0}   {1}   {2}   : {0}   {1}   ]]\n[[   {3}   {4}   {5}   : {3}   {4}   ]]\n[[   {6}   {7}   {8}   : {6}   {7}   ]] ".format(a00,a01,t,a10,a11,t1,a20,a21,t2))
print()
print("calculando o 'Dz' ")
dzp = (a00 * a11 * t2) + (a01 * t1 * a20) + (t * a10 * a21)
dzs = (t * a11 * a20) + (a00 * t1 * a21) + (a01 * a10 * t2)
dz = (dzp) - (dzs)
print("diagonal principal do 'Dz' deu: ", dzp)
print("diagonal secundaria do 'Dz' deu: ", dzs)
print("resultado de 'Dz' eh: ", dz)
if (d != 0):
    caldx = dx/d
    print("\nno resultado de D× dividido por D eh: {0} \n".format(caldx))
    caldy = dy/d
    print("\nno resultado de Dy dividido por D eh: {0}\n".format(caldy))
    caldz = dz/d
    print("\nno resultado de Dz dividido por D eh: {0}\n".format(caldz))
    print()
    print("[{0}, {1}, {2}]".format(caldx,caldy,caldz))
    if (d != 0 ) and (dx != 0) and (dy != 0):
        print("sistema possivel determinado 'SPD' ")
if (d == 0):
    print("imposivel haver divisao")
    if (d==0) and (dx==0) and (dy==0):
        print("\nsistema possivel inderterminado 'SPI' ['D' {0},  'Dx' {1},  'Dy' {2},  'Dz' {3}] ".format(d,dx,dy,dz))
    else:
        print("sistema iderterminado 'SI' ['D' {0},  'Dx' {1},  'Dy' {2},  'Dz' {3}] ".format(d,dx,dy,dz))